GET http://localhost:8000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJudmNBbVdpZnpWcDhlR284VGVpbzJXOW9PNDJLd3NpdyIsInN1YiI6IjEyMzQ1Njc4OTAiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MTkwNzcxMDM0MX0.DpVDqKlRGMpFOIWVcShde12ea7Ccl6yigBEBxptDVmQ